'use strict';
const assert=require('assert');
const {SEMANTIC_IR_SCHEMA_VERSION,SEMANTIC_FIELDS}=require('./semantic_ir_schema_v0.1.js');
const {NEAREST_NEIGHBOR_STATUS,reviewNearestNeighbors}=require('./semantic_ir_nearest_neighbor_v0.1.js');
function makeIR(fields={}){return {schema_version:SEMANTIC_IR_SCHEMA_VERSION,raw_input:'宿命 回去 求人 医生 悲伤',fields:Object.fromEntries(SEMANTIC_FIELDS.map(f=>[f,Object.prototype.hasOwnProperty.call(fields,f)?fields[f]:null]))};}
const tests=[]; const t=(n,f)=>tests.push([n,f]);
t('no reviews never auto-confirms candidate',()=>assert.strictEqual(reviewNearestNeighbors(makeIR(),{candidate_symbol:'nx',reviews:[]}).status,NEAREST_NEIGHBOR_STATUS.NEEDS_MORE_STRUCTURE));
t('unknown checked field value asks for more structure',()=>{const r=reviewNearestNeighbors(makeIR({actor:'A'}),{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'EXCLUDED',checked_fields:['changed_variable']}]}); assert.strictEqual(r.status,NEAREST_NEIGHBOR_STATUS.NEEDS_MORE_STRUCTURE); assert.deepStrictEqual(r.missing_fields,['changed_variable']);});
t('not-excluded neighbor returns ambiguous',()=>assert.strictEqual(reviewNearestNeighbors(makeIR({changed_variable:'v'}),{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'NOT_EXCLUDED',checked_fields:['changed_variable']}]}).status,NEAREST_NEIGHBOR_STATUS.AMBIGUOUS));
t('unknown review outcome returns needs more structure',()=>assert.strictEqual(reviewNearestNeighbors(makeIR({changed_variable:'v'}),{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'UNKNOWN',checked_fields:['changed_variable']}]}).status,NEAREST_NEIGHBOR_STATUS.NEEDS_MORE_STRUCTURE));
t('all declared neighbors excluded passes hook',()=>assert.strictEqual(reviewNearestNeighbors(makeIR({changed_variable:'v',relation_source:'self'}),{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'EXCLUDED',checked_fields:['changed_variable']},{neighbor_symbol:'x',outcome:'EXCLUDED',checked_fields:['relation_source']}]}).status,NEAREST_NEIGHBOR_STATUS.EXCLUDED));
t('surface keywords do not affect result',()=>{const ir=makeIR({changed_variable:'v'}); const a=reviewNearestNeighbors(ir,{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'EXCLUDED',checked_fields:['changed_variable']}]}); const b=reviewNearestNeighbors({...ir,raw_input:'赛博朋克宿命医生死亡回去求人'},{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'EXCLUDED',checked_fields:['changed_variable']}]}); assert.deepStrictEqual(a,b);});
t('x并z remains atomic canonical candidate',()=>assert.strictEqual(reviewNearestNeighbors(makeIR({object_layer:'L'}),{candidate_symbol:'x并z',reviews:[{neighbor_symbol:'n',outcome:'EXCLUDED',checked_fields:['object_layer']}]}).candidate_symbol,'x并z'));
t('invented x+z candidate hard fails',()=>assert.throws(()=>reviewNearestNeighbors(makeIR(),{candidate_symbol:'x+z',reviews:[{neighbor_symbol:'n',outcome:'EXCLUDED',checked_fields:['object_layer']}]}),e=>e.code==='ERROR_IR_NN_CANDIDATE_UNKNOWN'));
t('neighbor cannot equal candidate',()=>assert.throws(()=>reviewNearestNeighbors(makeIR({object_layer:'L'}),{candidate_symbol:'n',reviews:[{neighbor_symbol:'n',outcome:'EXCLUDED',checked_fields:['object_layer']}]}),e=>e.code==='ERROR_IR_NN_SAME_SYMBOL'));
t('non-IR checked field hard fails',()=>assert.throws(()=>reviewNearestNeighbors(makeIR({actor:'A'}),{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'EXCLUDED',checked_fields:['emotion']}]}),e=>e.code==='ERROR_IR_NN_FIELD_UNKNOWN'));
t('data blocked wins before reviews',()=>assert.strictEqual(reviewNearestNeighbors(makeIR(),{data_blocked:true,candidate_symbol:'nx',reviews:[]}).status,NEAREST_NEIGHBOR_STATUS.DATA_BLOCKED));
t('invalid outcome hard fails',()=>assert.throws(()=>reviewNearestNeighbors(makeIR({actor:'A'}),{candidate_symbol:'nx',reviews:[{neighbor_symbol:'zx',outcome:'MAYBE',checked_fields:['actor']}]}),e=>e.code==='ERROR_IR_NN_OUTCOME'));
let passed=0;for(const [name,fn] of tests){try{fn();passed++;}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
console.log(JSON.stringify({suite:'semantic_ir_nearest_neighbor_v0.1',tests:tests.length,passed,failed:tests.length-passed,target:'P0-5 nearest-neighbor exclusion hook; no theory invention; unresolved neighbors block hard selection'},null,2));
